name: manage-azure-policy-230c1d92
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/OriginalMindtreePolicy_57337df6-43d0-4114-8ef4-1b1893f2f74b/**'
#      - .github/workflows/manage-azure-policy-230c1d92.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_230c1d92}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/OriginalMindtreePolicy_57337df6-43d0-4114-8ef4-1b1893f2f74b/**
